RepositorioProyecto/proyectoFinal/apps/noticias/urls.py
from django.urls import path, include
from . import views

app_name='noticias'

urlpatterns = [
    path('Crear', views.CrearNoticia.as_view(), name="crear_noticia"),

    path('Listar', views.ListarNoticias.as_view(), name="listar_noticias"),
]

RepositorioProyecto/proyectoFinal/apps/usuarios/urls.py
from django.urls import path, include
from . import views

app_name='usuarios'

urlpatterns = [
    path('Registro', views.Registro.as_view(), name="registrar"),
]

RepositorioProyecto/proyectoFinal/proyectoFinal/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth

from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home, name = 'home'),

    #URLS DE AUTH
    path('login/',auth.LoginView.as_view(template_name='usuarios/login.html'),name='login'),
    path('logout/',auth.LogoutView.as_view(),name="logout"),

    #URLS DE USUARIOS
    path('usuarios/', include('apps.usuarios.urls')),

    #URLS DE NOTICIAS
    path('noticias/', include('apps.noticias.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RepositorioProyecto/proyectoFinal/apps/noticias/models.py
from django.db import models
from django.contrib.auth.models import User

class Categoria(models.Model):
	nombre = models.CharField(max_length=80)

	def __str__(self):
		return self.nombre

class Noticia(models.Model):
	creado = models.DateTimeField(
		'creado',
		auto_now_add=True
	)
	modificado = models.DateTimeField(
		'modificado',
		auto_now=True
	)
	titulo = models.CharField(max_length = 250)
	contenido = models.TextField()
	autor = models.ForeignKey(User, on_delete = models.CASCADE)
	imagen = models.ImageField(upload_to = 'noticias')
	categoria = models.ForeignKey(Categoria, on_delete = models.CASCADE)

	def __str__(self):
		return self.titulo

RepositorioProyecto/proyectoFinal/apps/usuarios/models.py
from django.db import models

# Create your models here.

RepositorioProyecto/proyectoFinal/apps/noticias/forms.py
from django import forms
from .models import Noticia


class Form_Alta(forms.ModelForm):

    class Meta:
        model = Noticia
        fields = ('titulo','contenido','imagen','categoria')

        
        

RepositorioProyecto/proyectoFinal/apps/usuarios/forms.py
from django import forms


from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegistroForm(UserCreationForm):
    email = forms.EmailField(label='Correo', required=True)
    first_name = forms.CharField(label='Nombre', required=True)
    last_name = forms.CharField(label='Apellido', required=True)
    password1 = forms.CharField(
        label='Contraseña', widget=forms.PasswordInput, required=True)
    password2 = forms.CharField(
        label='Confirmar Contraseña', widget=forms.PasswordInput, required=True)

    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2'
        ]

RepositorioProyecto/proyectoFinal/apps/noticias/views.py
from django.shortcuts import render
from django.views.generic import CreateView, ListView
from django.urls import reverse_lazy

from .models import Noticia
from .forms import Form_Alta

#CONTROLA SI EL USUARIO ESTA LOGEADO
from django.contrib.auth.mixins import LoginRequiredMixin

class CrearNoticia(LoginRequiredMixin, CreateView):
	model = Noticia
	form_class = Form_Alta
	template_name = 'noticias/crear.html'
	success_url = reverse_lazy('noticias:listar_noticias')
	
	def form_valid(self, form):
		noticia = form.save(commit=False)
		noticia.autor = self.request.user
		return super(CrearNoticia, self).form_valid(form)


class ListarNoticias(ListView):
	model = Noticia
	template_name = 'noticias/listar.html'
	#POR DEFECTO ESTA VISTA MANDA AL TEMPLATE UNA VARIABLE
	#LLAMADA OBJECT_LIST, CON LA LISTA DE TODAS LAS NOTICIAS

RepositorioProyecto/proyectoFinal/apps/usuarios/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import RegistroForm
# Create your views here.



class Registro(CreateView):
	#FORMULARIO DJANGO
	form_class = RegistroForm
	success_url = reverse_lazy('login')
	template_name = 'usuarios/registro.html'

RepositorioProyecto/proyectoFinal/proyectoFinal/views.py
from django.shortcuts import render


def Home(request):

	return render(request,'inicio.html')

RepositorioProyecto/proyectoFinal/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>PROYECTO 2023</title>
<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
</head>
<body class="fondo">

	<div class="container">
		<div class="row">
			<img src="{% static 'img/logo.png' %}" width="100" height="100">
			<h1 class="titulo ml-3">PROYECTO INFORMATORIO 2023</h1>
		</div>
		<div>
			<a href="{% url 'home' %}">Home</a>
			{% if user.is_authenticated %}
				HOLA COMO ESTAS? {{user.username}}
				<a href="{% url 'logout' %}">Salir</a>
			{% else %}
				<a href="{% url 'login' %}">Login</a>
				<a href="{% url 'usuarios:registrar' %}">registrame</a>
			{% endif %}
			<a href="{% url 'noticias:crear_noticia' %}">Crear Noticia</a>
			<a href="{% url 'noticias:listar_noticias' %}">LISTAR</a>
		</div>
	</div>
	<div class="container p-3">
	{% block contenido %}

	{% endblock contenido %}
	</div>

</body>
</html>

RepositorioProyecto/proyectoFinal/templates/inicio.html
{% extends 'base.html' %}


{% block contenido %}
	ESTE ES EL INICIO
{% endblock contenido %}

RepositorioProyecto/proyectoFinal/templates/noticias/crear.html
{% extends 'base.html' %}
{% load static %}
{% block contenido %}

<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto mb-5">
        <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}         
         <h3 class="mb-4">CREAR NOTICIA</h3>
          {{form.as_p}}
          <p><input type="submit" class="btn btn-primary btn-block" value="Confirmar"></p>
        </form>
      </div>
    </div>
  </div>
</main>
{% endblock contenido %}

RepositorioProyecto/proyectoFinal/templates/noticias/listar.html
{% extends 'base.html' %}


{% block contenido %}
	
	<div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto mb-5">
      	{% for n in object_list %}
      		<div>
      			<h4>CATEGORIA: {{n.categoria}}</h4>
      			<h4>FECHA: {{n.creado}}</h4>
      			<img src="{{n.imagen.url}}" width="200">
      			<h4>TITULO: {{n.titulo}}</h4>
      			<h4>CONTENIDO: {{n.contenido}}</h4>
      			<h4>AUTOR: {{n.autor}}</h4>
      			<hr>
      		</div>
      	{% endfor %}

      </div>
    </div>
  </div>

{% endblock contenido %}

RepositorioProyecto/proyectoFinal/templates/usuarios/login.html
{% extends 'base.html' %}

{% block contenido %}
			<form method="POST">{%csrf_token%}
				{{form.errors}}
				<input type="text" name="username" placeholder="USUARIO">
				<input type="password" name="password" placeholder="PASSWORD">

				<input type="submit" name="" value="ENVIAR">
			</form>
{% endblock %}

RepositorioProyecto/proyectoFinal/templates/usuarios/registro.html
{% extends 'base.html' %}
{% load static %}
{% block contenido %}

<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto mb-5">
        <form action="" method="post">{% csrf_token %}         
         <h3 class="mb-4">Registro</h3>
          {{form.as_p}}
          <p><input type="submit" class="btn btn-primary btn-block" value="Confirmar"></p>
        </form>
      </div>
    </div>
  </div>
</main>
{% endblock contenido %}